FROM python:3.10-alpine3.19

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./backend/src /code/src

CMD ["fastapi", "run", "src/main.py", "--port", "8000"]